Update pre-train model URL(faster rcnn and mask rcnn)
open-mmlab/mmdetection pull request #4307
Opened 2020-12-15 04:37 UTC by hhaAndroid

update pre-train model URL(faster rcnn and mask rcnn)

2020-12-15 07:16 UTC, ZwwWayne approved these changes

2020-12-15 08:09 UTC, hellock requested changes
There is a linting error.

2020-12-20 05:31 UTC, ZwwWayne commented
Please fix the linting error and also update the performance of these two new models.

2020-12-21 06:57 UTC, ZwwWayne commented on configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco-person.py
> +_base_ = './faster_rcnn_r50_caffe_fpn_mstrain_1x_coco.py'
Rename the configs to be `faster_rcnn_r50_fpn_mstrain_1x_coco-person.py`

2020-12-21 06:57 UTC, ZwwWayne commented on configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco-person-bicycle-car.py
> -_base_ = './faster_rcnn_r50_fpn_1x_coco.py'
Rename the file to be `faster_rcnn_r50_fpn_1x_coco-person-bicycle-car.py`

2020-12-22 06:51 UTC, hellock approved these changes

2020-12-22 06:53 UTC, merged