Fcos num pos
open-mmlab/mmdetection pull request #4370
Opened 2020-12-30 02:33 UTC by yhcao6

| Model             | 4GPU | 8GPU |
|-------------------|------|------|
| R50-GN-1x         | 36.6 | 36.7 |
| R50-GN-mstrain-2x | 38.7 | 38.5 |

2020-12-30 02:53 UTC, hiyyg commented
Why is FCOS in mmdet much worse than that of adet (https://github.com/aim-uofa/AdelaiDet/tree/master/configs/FCOS-Detection)?

2020-12-30 03:05 UTC, yhcao6 commented
> Why is FCOS in mmdet much worse than that of adet (https://github.com/aim-uofa/AdelaiDet/tree/master/configs/FCOS-Detection)?

We don't use all tricks.

2020-12-30 03:07 UTC, hiyyg commented
why not?

2020-12-30 03:21 UTC, yhcao6 commented
> why not?

We have implemented these tricks, you can refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_coco.py.
The baseline config should be consistent with the precision in the original paper. https://arxiv.org/abs/1904.01355
This Pr aims to supports training with 8 GPU without the precision drop. I just picked several models for testing.

2021-01-01 07:08 UTC, shinya7y commented on mmdet/models/dense_heads/fcos_head.py
> +        num_pos = max(reduce_mean(torch.tensor(num_pos).cuda()).item(), 1.0)
Casting like the below may be needed for PyTorch 1.6+. https://github.com/open-mmlab/mmdetection/pull/4210
``` python
num_pos = torch.tensor(num_pos, dtype=torch.float, device=bbox_preds[0].device)
num_pos = max(reduce_mean(num_pos).item(), 1.0)
```

2021-01-01 07:12 UTC, shinya7y commented on mmdet/models/dense_heads/fcos_head.py
>              avg_factor=num_pos + num_imgs)  # avoid num_pos is 0
`# avoid num_pos is 0` becomes inconsistent with the code.
Is ` + num_imgs` still needed for AP?

2021-01-03 11:29 UTC, shinya7y requested changes
https://github.com/open-mmlab/mmdetection/blob/cd00b884759a2572021461e7e8204f364581e01d/mmdet/models/dense_heads/fcos_head.py#L230
``` python
if len(pos_inds) > 0:
```

2021-01-03 11:55 UTC, shinya7y reviewed
Many dependencies in the HRNet directory.
https://github.com/open-mmlab/mmdetection/tree/cd00b884759a2572021461e7e8204f364581e01d/configs/hrnet
https://github.com/open-mmlab/mmdetection/tree/cd00b884759a2572021461e7e8204f364581e01d/configs/hrnet/fcos_hrnetv2p_w32_gn-head_4x4_1x_coco.py

Updating config links and Notes in the FCOS README is also needed.

2021-01-27 02:50 UTC, ZwwWayne approved these changes

2021-01-27 02:50 UTC, merged