[Docs] add Chinese version of data_pipline
open-mmlab/mmdetection pull request #5662
Opened 2021-07-21 05:28 UTC by BIGWangYuDong

add Chinese version of data_pipline

2021-07-21 09:39 UTC, AronLin commented on docs_zh-CN/tutorials/data_pipeline.md
> +按照通常的惯例，我们使用 `Dataset` 和 `DataLoader` 做多线程的数据加载。`Dataset` 返回一个数据内容的字典，里面对应于模型前传方法的各个参数。因为在目标检测中，输入的图像数据具有不同的大小，我们在 `MMCV` 里引入一个新的 `DataContainer` 类别去帮助收集和分发不同大小的输入数据。更多细节请参考[这里](https://github.com/op
_按照惯例/通常_，我们使用 `Dataset` 和 `DataLoader`  _进行_ 多线程的数据加载。`Dataset` 返回 _字典类型的数据_，_数据内容为模型 forward_ 方法的各个参数。_由于_ 在目标检测中，输入的图像数据具有不同的大小，我们在 `MMCV` 里引入一个新的 `DataContainer`  _类_ 去收集和分发不同大小的输入数据。更多细节请参考[这里](https://github.com/open-mmlab/mmcv/blob/master/mmcv/parallel/data_container.py)。

2021-07-21 09:39 UTC, AronLin commented on docs_zh-CN/tutorials/data_pipeline.md
> +下面的例子就是 `Faster R-CNN` 的一个流程：
delete `就`

2021-07-21 09:39 UTC, AronLin commented on docs_zh-CN/tutorials/data_pipeline.md
> +- 更新：由 `keys` 指定。
Unify the periods at the end of the sentence.

2021-07-21 09:39 UTC, AronLin commented on docs_zh-CN/tutorials/data_pipeline.md
> +- 更新：img, gt_bboxes, gt_labels
Unify the periods at the end of the sentence.

2021-07-21 09:39 UTC, AronLin commented on docs_zh-CN/tutorials/data_pipeline.md
> +1. 在任何一个文件里写一个新的流程，例如 `my_pipeline.py`。它以一个字典作为输入并且输出一个字典。
任意文件

2021-07-23 07:17 UTC, jshilong commented on docs_zh-CN/tutorials/data_pipeline.md
> +2. 导入一个新类。
导入一个新类，确保程序启动时会被注册进 PIPELINES

2021-07-28 10:55 UTC, AronLin commented on docs_zh-CN/tutorials/data_pipeline.md
> +按照惯例，我们使用 `Dataset` 和 `DataLoader` 进行多线程的数据加载。`Dataset` 返回字典类型的数据，数据内容为模型 `forward` 方法的各个参数。由于在目标检测中，输入的图像数据具有不同的大小，我们在 `MMCV` 里引入一个新的 `DataContainer` 类 去收集和分发不同大小的输入数据。更多细节请参考[这里](https://github.com
`类 去`
space

2021-07-28 10:55 UTC, AronLin commented on docs_zh-CN/tutorials/data_pipeline.md
> +- 增加：img_meta（img_meta 的键（key）被 `meta_keys` 指定)
img_metas

2021-07-28 10:55 UTC, AronLin commented on docs_zh-CN/tutorials/data_pipeline.md
> +2. 导入一个新类，确保程序启动时会被注册进 PIPELINES：
导入 _这个_ 新类，确保程序启动时 _它_ 会被注册进 PIPELINES：

2021-08-04 03:41 UTC, AronLin approved these changes

2021-08-09 08:42 UTC, jshilong requested changes

2021-08-09 08:42 UTC, jshilong commented on docs_zh-CN/tutorials/data_pipeline.md
> +按照惯例，我们使用 `Dataset` 和 `DataLoader` 进行多线程的数据加载。`Dataset` 返回字典类型的数据，数据内容为模型 `forward` 方法的各个参数。由于在目标检测中，输入的图像数据具有不同的大小，我们在 `MMCV` 里引入一个新的 `DataContainer` 类去收集和分发不同大小的输入数据。更多细节请参考[这里](https://github.com/
多进程

2021-08-09 08:43 UTC, jshilong approved these changes

2021-08-11 07:26 UTC, ZwwWayne approved these changes

2021-08-11 07:26 UTC, merged