add Chinese version of init_cfg
open-mmlab/mmdetection pull request #7188
Opened 2022-02-17 11:43 UTC by yarkable

Translate the init_cfg.md doc to Chinese

2022-02-17 11:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmdetection?pullRequest=7188) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmdetection?pullRequest=7188) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmdetection?pullRequest=7188) it.</sub>

2022-02-22 01:58 UTC, hhaAndroid commented on docs/zh_cn/tutorials/init_cfg.md
> +2. 像往常一样构建模型，但显式调⽤ `model.init_weights()` ⽅法，并且模型参数将被初始化为配置。
```suggestion
2. 像往常一样构建模型，然后显式调⽤ `model.init_weights()` ⽅法，此时模型参数将会被按照配置文件写法进行初始化。
```

2022-02-22 02:02 UTC, hhaAndroid commented on docs/zh_cn/tutorials/init_cfg.md
> +MMdetection 中初始化的⾼级⼯作流程是：
MMdetection 初始化工作流的高层 API 调用流程是：

2022-02-22 02:03 UTC, hhaAndroid commented
@yarkable Please fix the lint first

2022-02-22 02:15 UTC, zytx121 requested changes
Error operation, please ignore.

2022-02-22 02:20 UTC, zytx121 commented
Hi @yarkable  
You can use pre-commit to fix lint errors by run `pre-commit run --all-files`

2022-02-22 02:21 UTC, Czm369 approved these changes
LGTM

2022-02-22 02:28 UTC, zytx121 commented on docs/zh_cn/tutorials/init_cfg.md
> +- `override` (dict or list[dict])，包含不继承⾃ `BaseModule` 且其初始化配置与 `layer` 键中的其他层不同的⼦模块。 `type` 中定义的初始化器将适⽤于 `layer` 中定义的所有层，因此如果⼦模块不是 `BaseModule` 的派⽣类但可以与 `layer` 中的层相同的⽅式初始化，则不需要使⽤ `override`。`overrid
- `override` (dict 或 list[dict])

2022-02-22 02:33 UTC, zytx121 commented on docs/zh_cn/tutorials/init_cfg.md
> +- `type` (str)，包含 `INTIALIZERS` 中的初始化程序名称，后面跟着初始化程序的参数。
- `type` (str)，包含 `INTIALIZERS` 中的初始化器的名称，以及后面跟着的初始化器的参数。

2022-02-22 02:51 UTC, zytx121 commented on docs/zh_cn/tutorials/init_cfg.md
> +- 如果 init_cfg 中的 `layer` 为 None，则只会初始化 override 中名称的⼦模块，⽽ override 中的 type 和其他参数可以省略。
- 如果 init_cfg 中的 `layer` 为 None，则只会初始化 override 中有名称的⼦模块，⽽ override 中的 type 和其他参数可以省略。

2022-02-22 03:53 UTC, yarkable commented
pre-commit run --all-files

2022-02-22 05:08 UTC, yarkable commented on docs/zh_cn/tutorials/init_cfg.md
> +
OK

2022-02-22 05:33 UTC, yarkable commented
pre-commit run --all-files

2022-02-22 09:13 UTC, zytx121 commented
Hi @yarkable 
Please refer to https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md for proper use of pre-commit.

2022-02-22 13:32 UTC, yarkable commented
> 

Thanks a lot! It's all passed now.

```bash
[WARNING] The 'rev' field of repo 'https://github.com/open-mmlab/pre-commit-hooks' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
flake8...................................................................Passed
seed isort known_third_party.............................................Passed
isort....................................................................Passed
yapf.....................................................................Passed
Trim Trailing Whitespace.................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Fix requirements.txt.....................................................Passed
Fix double quoted strings................................................Passed
Check for merge conflicts................................................Passed
Fix python encoding pragma...............................................Passed
Mixed line ending........................................................Passed
Markdownlint.............................................................Passed
codespell................................................................Passed
docformatter.............................................................Passed
check algorithm readme...................................................Passed
check copyright..........................................................Passed
```

2022-02-23 03:38 UTC, zytx121 approved these changes

2022-02-23 03:39 UTC, zytx121 commented
LGTM.

2022-02-23 03:48 UTC, BIGWangYuDong commented on docs/zh_cn/tutorials/init_cfg.md
> +  init_cfg = dict(type='Constant', layer ['Conv1d','Conv2d'], val=1, bias=2,
miss `=` here : layer=['Conv1d','Conv2d']

2022-02-23 03:48 UTC, BIGWangYuDong commented on docs/zh_cn/tutorials/init_cfg.md
> +  init_cfg = dict(type='Constant', layer ['Conv1d','Conv2d'], val=1, bias=2,
layer=['Conv1d','Conv2d']
Also, please fix this error in English version

2022-02-23 03:50 UTC, BIGWangYuDong commented
@yarkable Please remember to add `=` in the English version document at the same time.

2022-02-23 12:55 UTC, yarkable commented
> @yarkable Please remember to add `=` in the English version document at the same time.

Fixed now.

2022-02-24 06:19 UTC, merged